name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional Sonar scan
      - name: SonarCloud Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./angularapp
          args: >
            -Dsonar.projectKey=myproject
            -Dsonar.organization=myorg
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build Angular App
        run: |
          cd angularapp
          npm install
          npm run build --prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-dist
          path: angularapp/dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./angularapp
          file: ./angularapp/docker/Dockerfile
          push: true
          tags: ajitsinghkaurav/my-angular-app:latest
